services:
  - type: web
    name: centurion-complaint-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: MAX_FILE_SIZE_MB
        value: "5"
      - key: JWT_SECRET
        sync: false
      - key: TOKEN_EXPIRES_IN
        value: "2d"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
